### PR TITLE
feat: Add `skip_bits` and `skip_bytes` attribute

### LINKED ISSUE #12: Add support for unused/padding bits
It would be nice if there was a way to skip over bits or bytes without creating dummy fields in order to save on space e.g : 
```Rust
pub struct SomeStruct {
    field_01: u8,

    // This field is useless but is needed for proper read/write
    unused01: u8,

    field_02: u8,

    // This field is useless but is needed for proper read/write
    unused02: u8,
}
```

maybe some `skip_[bytes|bits]` that could be added before and after fields in structs :
```Rust
#[deku(skip_bytes="1")]
```

### PR DESCRIPTION
**Pull request by sharksforarms**
Fixes #12

### CODE REVIEW

**Comment by sharksforarms** [comment]
Still unsure about this one. Currently this only skips on read, should it "skip" or "pad" with something on write? Thoughts? @passcod

**Comment by inspier** [comment]
Personally, having it also "pad" on write would be nice, since generally for the formats I am working with, you want the padding to be preserved on serialization though the actual contents of the padding is unimportant. Strictly speaking you can implement this pad on write with custom writers too so thats not really a problem.

**Comment by passcod** [comment]
Certainly pad on write by default (with a custom writer to opt out), otherwise I think it's much less intuitive

**Comment by sharksforarms** [comment]
@inspier @passcod 

Thanks for the feedback. In that case, I propose 4 attributes instead:
- pad_bits_before: pad x bits before reading/writing (kinda long name...?)
- pad_before: pad x bytes before reading/writing
- pad_bits_after: pad x after reading/writing
- pad_after: pad x bytes after reading/writing
- pad_with: default: 0x00 for bytes, false for bits

**Comment by passcod** [comment]
That's comprehensive and covers everything I can think of. Only thing I'd say is I'm not sure if it should be `pad_after` or `pad_bytes_after`... the latter keeps in better with the other attributes that have bits and bytes versions without a clear "default"

**Comment by sharksforarms** [comment]
> That's comprehensive and covers everything I can think of. Only thing I'd say is I'm not sure if it should be `pad_after` or `pad_bytes_after`... the latter keeps in better with the other attributes that have bits and bytes versions without a clear "default"

Yeahh that's what I had it at first, was worried about the explicitness where most will be dealing with bytes over bits

**Comment by passcod** [comment]
Hmm, well, I can only offer my experience, where most of the cases I wish for it are when I read 2 bits and skip 6, that kinda thing. However, I don't have strong feelings either way.

**Comment by sharksforarms** [comment]
Closing in favour of the above attributes, stay tuned!

**Pull request closed without merging**
