### PR TITLE
Add support for raw identifiers

### PR DESCRIPTION
**Pull request by Visse**
Fixes: #220

### CODE REVIEW

**Review by sharksforarms — APPROVED** [review]
Thanks!

**Comment by sharksforarms** [comment]
Added in https://github.com/sharksforarms/deku/commit/511356a35cae9f4d40762bcbde0e2cca38f69543

**Comment by sharksforarms** [comment]
@Visse released in 0.12.1

**Comment by Visse** [comment]
Thanks for the quick handling!

**Pull request closed without merging**
