### PR TITLE
Use pass by value (1 byte vs 8 bytes)

### PR DESCRIPTION
**Pull request by wcampbell0x2a**

### CODE REVIEW

**Comment by sharksforarms** [comment]
Hey @wcampbell0x2a thanks for the PR! What are your intentions for the change? Performance? Code style?

This would make it consume ownership of the enum instead of borrowing it

**Comment by wcampbell0x2a** [comment]
> Hey @wcampbell0x2a thanks for the PR! What are your intentions for the change? Performance? Code style?
> 
> This would make it consume ownership of the enum instead of borrowing it

It was mostly for performance, I didn't think the consuming would be a problem for the API.

**Comment by sharksforarms** [comment]
I'm not sure the performance benefits (would be super minimal, if anything) outweigh the usefulness of the borrowing API, what do you think @constfold ? (Freshly merged code here)

**Comment by constfold** [comment]
Looks good to me.
> This would make it consume ownership of the enum instead of borrowing it

It's okay, `Endian` is `Copy`.

> I'm not sure the performance benefits (would be super minimal, if anything) 

`Endian` might be 1 bit, but a ref is always usize(4 bytes or 8 bytes). Maybe it's useful, in few cases.

**Pull request merged**
